### PR TITLE
Update Course Offering

### PR DESCRIPTION
**Pull request by Hgjnnf**
Update Course Offering in Course Review DB in accordance with UBC's 2023W Course Schedule.

Before: 
Screenshot 2023-07-31 010035
Screenshot 2023-07-31 010045
Screenshot 2023-07-31 010053
Screenshot 2023-07-31 010013
Screenshot 2023-07-31 010026

After: 
Screenshot 2023-07-31 005356
Screenshot 2023-07-31 005409
Screenshot 2023-07-31 005459
Screenshot 2023-07-31 005516
Screenshot 2023-07-31 005344

### CODE REVIEW

**Review by kewbish — COMMENTED** [review]
Looks good, thank you!

Could you try running:
```
$ git config core.eol lf
$ git config core.autocrlf input
```
in your Git Bash? I think you might be on Windows (?) and there's something off with some files' EOF.

Also, some files had their permissions changed - could you just remove them from the diff so that there's only the actual content changes (only the changes to `content/services/courses`)?

Thank you!

**Comment by Hgjnnf** [comment]
> Looks good, thank you!
> 
> Could you try running:
> 
> ```
> $ git config core.eol lf
> $ git config core.autocrlf input
> ```
> 
> in your Git Bash? I think you might be on Windows (?) and there's something off with some files' EOF.
> 
> Also, some files had their permissions changed - could you just remove them from the diff so that there's only the actual content changes (only the changes to `content/services/courses`)?
> 
> Thank you!

Yep, I am using Windows. How do I remove files from the diff? I couldn't find much info about online.

**Comment by kewbish** [comment]
> Yep, I am using Windows. How do I remove files from the diff? I couldn't find much info about online.

You can `git reset --soft origin/master` and `git restore --staged [filename]` for each of the files that have extraneous diffs. Then you can commit again (without running `git add .`) and push that. 

LMK if this still doesn't work and I'll help troubleshoot more!

**Comment by kewbish** [comment]
Could you try ^ with `git restore --staged .` and then `git add content/services/courses`? I'm not sure why Git is still staging the empty diffs in `static/files`.

**Comment by Hgjnnf** [comment]
> Could you try ^ with `git restore --staged .` and then `git add content/services/courses`? I'm not sure why Git is still staging the empty diffs in `static/files`.

This didn't work for me. I also tried going back to the previous commit and redoing everything inside content/services/courses. Didn't seem to work.

**Comment by Hgjnnf** [comment]
Closing PR to restart the task.

**Pull request closed without merging**
