### PR TITLE
Academic 110 blogpost

### PR DESCRIPTION
**Pull request by wgervasio**

### CODE REVIEW

**Review by kewbish — APPROVED** [review]
Please address Shubh's comments above (and wait for others to review content as per Slack), but approving this pre-emptively so we don't block publishing once it's ready!

**Comment by wgervasio** [comment]
Not yet, I got sidetracked with interviews I'll edit a bit more then re ping

**Comment by shubhbhalla** [comment]
@wgervasio Any updates on this?

**Comment by AnimeAllstar** [comment]
closing this due to inactivity.

**Comment by wgervasio** [comment]
Aight I'll recommit this with the new staff

**Pull request closed without merging**
