### PR TITLE
Add Google Programmable Search and remove navbar rotation

### LINKED ISSUE #21: Add search
Add a search bar to the website using [Algolia](https://www.algolia.com/) or a Google custom search.

### PR DESCRIPTION
**Pull request by RamitKataria**
Resolves #21 

Before approving, we should transfer the ownership of the search engine to the CSSS Google account and make sure it's approved as a non-profit by Google so that there are no ads.

For now, I have shadowed the header in the theme. What was our final decision on maintaining the theme ourself? If we're going ahead, then I can create a fork under this organization and make the change there.

Also, let me know if you have suggestions about the look & feel or anything else!

### CODE REVIEW

**Comment by AnimeAllstar** [comment]
Could you publish the branch to upstream, it'd be easier to checkout rather than cloning the fork?

**Comment by AnimeAllstar** [comment]
I think we should fork the theme, cause otherwise, we're going to keep overwriting the theme and it makes it harder to keep track of stuff.

**Comment by RamitKataria** [comment]
> @RamitKataria Could you publish the branch to upstream, it'd be easier to checkout to rather than cloning the fork?
I could but I thought we supposed to not make branches in this repo? Has the guideline changed?

> I think we should fork the theme, cause otherwise, we're going to keep overwriting the theme and it makes it harder to keep track of stuff.
Ok, I'll do that then, probably tomorrow.

**Comment by RamitKataria** [comment]
Also, I'm not sure why the Netlify checks are failing. [The logs](https://app.netlify.com/sites/ubccsss/deploys/61fd774ef6ebc20007242218) look fine and it deployed fine on [my instance](https://gcse-search--ramit-csss.netlify.app/) as well. @eqfy do you have access to the Netlify account? If so, could you check if it's showing any errors there?

**Comment by kewbish** [comment]
I think it's managed to build now - it looks good to me, really cool work! A nitpick: is there any way with CSS we could disable the background box of the search? It looks a bit out of place with the flat styling of the rest of the website.

Maybe:
```css
.gsc-control-cse-en {
    background: transparent;
    border: none;
}
```
could work.

**Comment by RamitKataria** [comment]
Thanks! It looks like the CSS file downloaded from Google is applied after our own so I added the `!important` keyword.

**Comment by RamitKataria** [comment]
New repo for the theme and [PR for the search-box](https://github.com/ubccsss/hugo-bootstrap-5/pull/1) created

**Comment by RamitKataria** [comment]
It now uses the site params to separate the production search from dev and preview so that the stats for production are more representative of actual usage.

**Comment by AnimeAllstar** [comment]
I do feel like we can improve the appearance of the search bar, but it works fine otherwise.

**Review by AnimeAllstar — COMMENTED** [review]
I do feel like we can improve the appearance of the search bar, but it works fine otherwise.

**Comment by eqfy** [comment]
> I do feel like we can improve the appearance of the search bar, but it works fine otherwise. We could make that another PR though.

@AnimeAllstar can make an issue for that when you have time?

I think everything looks good so far, we can probably merge things in

**Review by eqfy — APPROVED** [review]
Thanks @RamitKataria for the great work!

**Comment by RamitKataria** [comment]
@AnimeAllstar Thanks for noticing. In my testing, I resized it after loading the page but this issue only occurs if the page is loaded after resizing (which is what would happen in production). I'm not exactly sure why. It looks like the search box Google sends has different properties when it detects mobile. I guess we can make mobile specific changes to fix it later.

**Pull request merged**
