### PR TITLE
Added Companies from Rows 12 to 21

### PR DESCRIPTION
**Pull request by Anica1004**
Added Companies from Rows 12 to 21

### CODE REVIEW

**Comment by kewbish** [comment]
@Anica1004 could you please rebase this PR off of [this PR](https://github.com/ubccsss/ubccsss.org/pull/675)?

**Comment by Anica1004** [comment]
@kewbish Rebased and updated industry formatting for some companies!
Thanks :)

**Comment by chohyeonkim** [comment]
image
@Anica1004 hihi anica could you replace the trane logo with this instead? ( i think this has better resolution)  Thank you  !
https://www.stickpng.com/img/icons-logos-emojis/iconic-brands/trane-technologies-horizontal-logo

**Comment by Anica1004** [comment]
@chohyeonkim Just finished replacing the logo image! Thanks for catching that :) 

Screen Shot 2024-11-30 at 1 19 14 PM

**Review by kewbish — APPROVED** [review]
Thank you! Going to merge ASAP.

**Pull request merged**
