### PR TITLE
Add Cube Talks page

### PR DESCRIPTION
**Pull request by kewbish**
:warning: This PR is a draft, do not merge in.

Here's a draft of the Cube Talks pages. Note that only 'Episode 1: Scarlet Nguyen' has the YouTube video + audio linked up correctly (they just go to random placeholders on the Internet for now.)

I added everything we mentioned in the doc, but I left out the bullet point on putting Cube Talks in the services page. It has a CTA on the main page and is in the header navbar, and it doesn't fit as a 'service' IMO. 

To be done: once we have the podcast Gmail, set up the Google API key to use its account instead of mine. (I can do this once I have access to the account.) Google's API keys are meant to be public and the website and API-level gating occur on Google's side, so it's okay to commit the key to the repo. 

Let me know if you have any feedback!

### CODE REVIEW

**Comment by shubhbhalla** [comment]
Is it possible to remove the volunteer tab from the top bar? We don't need more volunteers for at least the next 4 months.

**Review by shubhbhalla — COMMENTED** [review]
The top bar should have a space for the title.
Screenshot 2023-03-06 at 1 25 56 PM

**Review by shubhbhalla — COMMENTED** [review]
Is it possible to remove the volunteer tab from the top bar? We don't need more volunteers for at least the next 4 months.

**Comment by shubhbhalla** [comment]
Can you make this text the intro para on the website?

`Introducing the newest addition to the Computer Science Student Society's engagement efforts - our very own podcast! Made by UBC students for UBC students, our bi-weekly podcast will feature UBC alumni and upper-year students as speakers, discussing topics relevant to all students interested in computer science, not just those in the major. We'll be diving deep into conversations with our guests and bringing you valuable insights into the tech industry. To ensure easy access, our podcasts will be available on all major podcast platforms. So, tune in and join us on this exciting new journey!`

**Comment by shubhbhalla** [comment]
Can you please add the cube-talks page in the services tab on teh website too?

**Comment by kewbish** [comment]
Done!

**Comment by shubhbhalla** [comment]
I was using the website on mobile and the picture of Scarlet looks elongated. Can we please fix this?image

**Comment by shubhbhalla** [comment]
Hey @kewbish thanks for the quick push!
Can you just push the picture to the top?
image

**Comment by shubhbhalla** [comment]
We finally have the [final video setup](https://www.youtube.com/watch?v=KeT7btOQizk)!
@kewbish  can you please hook up the correct video and view count to the website?
@RamitKataria Can you please hook up the correct audio file? Do you need a new one or can youtube give you the audio file out of this?

**Comment by shubhbhalla** [comment]
@kewbish Can you fix the 'reach out to them here' link to https://www.linkedin.com/in/scarletnguyen/ ? 
Screenshot 2023-03-19 at 9 14 38 PM

**Comment by shubhbhalla** [comment]
This is the description you should use for the first episode - 

`In the first episode of Cube Talks, we interview the talented Scarlet Nguyen! With diverse internship experiences at big tech companies, Scarlet spills the beans on what it takes to impress hiring managers and land that dream job. But that's not all – she also shares insider tips on how to excel as an intern, from balancing personal projects to acing hackathons. Whether you're curious about the day-to-day life of a tech intern or just looking to up your game, this episode has something for you. So sit back, relax, and tune in to get the inside scoop on one of the industry's rising stars!`

**Comment by shubhbhalla** [comment]
there are only 2 things left now, embedding the audio file on the website and adding an 800x300 picture to the page for the cube talks! I will update you about the later when I have it :)

**Comment by shubhbhalla** [comment]
@kewbish the graphic is ready for the front page and it is located here - https://drive.google.com/file/d/1HzIhjIWKwbtSzMV-nB6LGGXLME5ebpYe/view?usp=drivesdk

@RamitKataria can you please upload the audio file and then we have everything finalized!

**Comment by RamitKataria** [comment]
I've added 4 embeds. Not sure which one looks the best. Here's my thoughts about the 4 in order:
1. Audio only but users can still click on it to open in spotify which shows an option to view video (if Spotify app installed)
2. Audio only but looks better on mobile than the other 3, imo
3. Includes video but doesn't seem to work on mobile
4. Audio only. Doesn't look as good as the other ones and clicking on it takes users to the website of hosting provider instead of the spotify app.

I'm leaning towards 1 and 2. Also, I wasn't sure where to put it so I made another collapse button but feel free to move it somewhere else.

**Comment by shubhbhalla** [comment]
@RamitKataria, great job! Let's go with 2. Can you also please add the description to episode 1 [that I have above?](https://github.com/ubccsss/ubccsss.org/pull/415#issuecomment-1476879858)
Also can you add the [picture](https://drive.google.com/file/d/1HzIhjIWKwbtSzMV-nB6LGGXLME5ebpYe/view?usp=drivesdk) to the home page of Cube talks? We can push this PR then

**Review by shubhbhalla — APPROVED** [review]
Looks great! Awesome job guys :)

**Pull request merged**
