### PR TITLE
Add TCF companies 22 to 31

### PR DESCRIPTION
**Pull request by andrew-fenton**
- Added companies and their logos to TCF page (need to assign booth numbers)
- Removed placeholders for empty company sections
- Uncommented and adjusted company sections to pull tcf-company-2025 layouts
- Updated 2023 company layouts to prevent conflicts

image

### CODE REVIEW

**Comment by kewbish** [comment]
@andrew-fenton TYSM! Do you mind rebasing off the latest master? I merged a commit to hide the booth numbers. 

We can then merge this PR first (to pull in the layout updates) then merge the other two PRs.

**Comment by andrew-fenton** [comment]
> @andrew-fenton TYSM! Do you mind rebasing off the latest master? I merged a commit to hide the booth numbers.
> 
> We can then merge this PR first (to pull in the layout updates) then merge the other two PRs.

Ok, rebased :)

**Review by kewbish — APPROVED** [review]

**Comment by kewbish** [comment]
(Think something might've gone awry with the rebase because Youssef's commit is now here, but should be perfectly fine once everything gets merged down.)

**Comment by wgervasio** [comment]
goat lineup

**Pull request merged**
