### PR TITLE
Add new batch of companies

### PR DESCRIPTION
**Pull request by kewbish**
This PR adds a new batch of companies as of 5 January 2023 per the spreadsheet (see Slack).

Several companies (CSIS, West Fraser Timber) did not provide logos, so I've found those online and will replace them in the next batch if different logos are provided. Several companies also have not been confirmed yet in Column E, and will be added in the next batch when confirmed.

### CODE REVIEW

**Comment by tommysteryy** [comment]
A few new logos were added this morning!

**Comment by kewbish** [comment]
@tommysteryy - just filled in the rest of the companies. Translink did not provide a logo, but I can replace it whenever they send it over.

Could you take a look?

**Comment by tommysteryy** [comment]
Finally got a chance to review it! This is really coming together, thanks so so much for all your work! 

Just a last few comments:
- Let's leave off `Translink` for now until they confirm with us on Monday! They'll send over a logo when they're ready as well.
- Is it just my eyes or are the rows of company profiles different sizes? I see it most in the row containing the `Communications Security Establishment`, where I think that logo is long and is dragging out the box. **Is there an _easy_ way to make all the squares the same size, regardless of logo size?** If not, don't worry about it!

**Comment by tommysteryy** [comment]
Another idea: **can we add a `number of companies` here?**

image

**Review by tommysteryy — APPROVED** [review]
Beautifully done! I think that's all I was looking for. Thanks so much @kewbish!

**Comment by kewbish** [comment]
No problem!

@ubccsss/website - could I get a quick approve? Tommy doesn't have write access :frowning:

**Review by AnimeAllstar — APPROVED** [review]

**Pull request merged**
