### PR TITLE
Add Dark Mode To Site

### PR DESCRIPTION
**Pull request by justindhillon**
I just added dark mode to the site. I put an icon in the header bar that toggles it on and off. I then created a cookie that saves your dark mode preference. I used the [dark reader](https://github.com/darkreader/darkreader) api to make this happen. I edited the header.html partial template and the global css file. The icons are unicode emojis. Here is a youtube video demonstrating my contributions:

https://youtu.be/yIsChD3tGxs

### CODE REVIEW

**Comment by kewbish** [comment]
Hello and thank you for your PR! Just a heads up that I plan to review this sometime next weekend, sorry for the wait!

**Comment by kewbish** [comment]
Did you get a chance to fix the toggle on mobile as we discussed?

**Comment by justindhillon** [comment]
@kewbish Dark mode is now ready for production. It now looks like a nice button, uses a local image to increase device compatibility, and behaves well on mobile.

**Comment by kewbish** [comment]
Thanks for the update. Where are the icon images taken from? Could you please check their licensing requirements?

Also, I made some updates to the button styling to more closely align with the rest of the site branding. LMK if this looks alright to you or if there were any specific points you wanted to keep from your previous iteration.

**Comment by justindhillon** [comment]
I replaced the icons with ones I made myself. I credit myself in the css file. This resolves #500. Button looks good to me!

**Review by kewbish — APPROVED** [review]
Thank you so much, looks good to me!

**Pull request merged**
