### PR TITLE
Delete ubccsss.org.iml

### PR DESCRIPTION
**Pull request by AnimeAllstar**
This is an IntelliJ module file used for keeping module configuration. Pretty sure that we can delete it, it shouldn't be committed.

### CODE REVIEW

**Comment by AnimeAllstar** [comment]
Merge on approval.

**Review by kewbish — APPROVED** [review]
Thank you!

**Comment by kewbish** [comment]
Could you also add it to `.gitignore`?

**Comment by AnimeAllstar** [comment]
@kewbish i don't think we need to. Usually this file is in `.idea/` and that is already in the `.gitignore`

**Pull request merged**
