### PR TITLE
Add course review dates

### PR DESCRIPTION
**Pull request by kewbish**
This PR adds course review dates to all the course reviews currently in the database. The dates were pulled directly from the Reddit / PRs / blog posts as appropriate.

For example:
image

### CODE REVIEW

**Comment by shubhbhalla** [comment]
@kewbish Does this mean that new reviews will also have dates?

**Comment by kewbish** [comment]
Not just yet - I'll add that to the GitHub issues worker when I add the [difficulty / overall quality ratings](https://docs.google.com/document/d/14f0MjqORObHDY3W9SO5eBsCPDFiuOzUMt2yis7kCCB0/edit?disco=AAAAdsd9xGU). (Will do later today or tomorrow.)

**Comment by AnimeAllstar** [comment]
@kewbish how do you plan on adding [difficulty / overall quality ratings](https://docs.google.com/document/d/14f0MjqORObHDY3W9SO5eBsCPDFiuOzUMt2yis7kCCB0/edit?disco=AAAAdsd9xGU)

**Comment by shubhbhalla** [comment]
> @kewbish how do you plan on adding [difficulty / overall quality ratings](https://docs.google.com/document/d/14f0MjqORObHDY3W9SO5eBsCPDFiuOzUMt2yis7kCCB0/edit?disco=AAAAdsd9xGU)

Also can we have a disclaimer before submitting a review saying that reviews may take anywhere from 1-5 days to process so that we can scan for malicious content?

**Comment by kewbish** [comment]
> @kewbish how do you plan on adding [difficulty / overall quality ratings](https://docs.google.com/document/d/14f0MjqORObHDY3W9SO5eBsCPDFiuOzUMt2yis7kCCB0/edit?disco=AAAAdsd9xGU)

Adding new fields to the worker / script / form. In terms of UI I was thinking a slider with a range of 1-5 with step of 0.5 but open to suggestions! I think these can be optional as we'd want to reduce friction to submit a review.

**Comment by kewbish** [comment]
> > @kewbish how do you plan on adding [difficulty / overall quality ratings](https://docs.google.com/document/d/14f0MjqORObHDY3W9SO5eBsCPDFiuOzUMt2yis7kCCB0/edit?disco=AAAAdsd9xGU)
> 
> Also can we have a disclaimer before submitting a review saying that reviews may take anywhere from 1-5 days to process so that we can scan for malicious content?

Yes, I can add that in the difficulty / quality PRs!

**Comment by shubhbhalla** [comment]
Can we do the rating and the disclaimer in this PR itself?

**Comment by AnimeAllstar** [comment]
> Can we do the rating and the disclaimer in this PR itself?

We need to make changes to the workers script if we want to add ratings, which is another repo. It's better we make another PR. 

@kewbish, let me know if you need any help with the cloudflare worker.

**Review by AnimeAllstar — APPROVED** [review]

**Comment by AnimeAllstar** [comment]
Also, let's try making issues for each PR.

**Comment by kewbish** [comment]
> @kewbish, let me know if you need any help with the cloudflare worker.

> I thought we wanted to make something more complex, but this works pretty nicely as well. The only drawback is not being able to ascertain that an individual is submitting multiple reviews for the same course.

Yes, will do - thanks!

I think we should stick to what we have for now instead of switching to something else - I'm wary of scope creep. With other systems, unless we had a login, we'd also not be able to confirm unique reviews. For example, for all we know the Reddit reviews on our site could be alts from the same user. For something small like this where we manually review each course anyways, I think we'll be fine as-is!

**Pull request merged**
