### PR TITLE
Add company row 2 ~ 11

### PR DESCRIPTION
**Pull request by chohyeonkim**
Add company row2 ~ 11

### CODE REVIEW

**Comment by chohyeonkim** [comment]
@kewbish , Could you confirm if amazon logo is the correct one?
image
image
the one from the logo folder has white background and logo itself is white as well,

**Comment by kewbish** [comment]
@chohyeonkim could you please rebase this PR off of [this PR](https://github.com/ubccsss/ubccsss.org/pull/675)? 

Re. Amazon logo: this is the correct one but since it's white, could you use [this one](https://en.m.wikipedia.org/wiki/File:Amazon_logo.svg) for now? I'll email to ask for an updated logo.

**Comment by chohyeonkim** [comment]
@kewbish Rebased and updated the logo! Let me know if it’s all good, and I’ll merge

**Comment by kewbish** [comment]
@chohyeonkim you might have to update the `imageLink` parameter to `/files/tcf2025/...` instead of `/files/tcf/...`, but otherwise looks good!

**Comment by chohyeonkim** [comment]
@kewbish thank you ! update the image link path

**Comment by chohyeonkim** [comment]
image
@andrew-fenton 
could you review this pr thank you !

**Comment by andrew-fenton** [comment]
Hey, could we change the BCLC logo to this one? It's a bit higher res.
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/BCLC_Logo.svg/760px-BCLC_Logo.svg.png?20190328043929

image

**Review by andrew-fenton — CHANGES_REQUESTED** [review]
Hey, could we change the BCLC logo to this one? It's a bit higher res.
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/BCLC_Logo.svg/760px-BCLC_Logo.svg.png?20190328043929

image

Other than that, looks good!

**Comment by chohyeonkim** [comment]
@andrew-fenton 
image

"Transportation and Distribution" "black" "Renewal Engery and Waste Management" "dark"

-> i can't seem to find other color which is not overlapped D: dark is supposed to be dark-grey but looks very close to black

**Review by andrew-fenton — APPROVED** [review]
looks good!

**Pull request merged**
