### PR TITLE
Tech Consulting Homepage

### PR DESCRIPTION
**Pull request by Hgjnnf**
Created the homepage for tech consulting based on tcf styling. Added 'About Us' and 'Projects' (used Lena's PR + some modification) sections.

Demo:

https://share.vidyard.com/watch/f7xPVN7Rcqr5tCbPavFeam?

### CODE REVIEW

**Comment by wgervasio** [comment]
Looks good to me, can you also populate the project names?

https://github.com/ubccsss/UBC-Tennis-Circle-Website
https://github.com/ubccsss/Live-Inventory-System
https://github.com/ubccsss/John-Frostad-Lab-Machinery-Controller
https://github.com/ubccsss/UBC-Volleyball-Club-Website
https://github.com/ubccsss/Blood-For-Life-Volunteer-Management-System

**Comment by kewbish** [comment]
@wgervasio I'm good to approve this if you're happy with everything!

**Comment by wgervasio** [comment]
@kewbish I'll take a look real quick!

**Comment by wgervasio** [comment]
@kewbish looks good to me! I'll follow-up on discord with the populated text fields by sunday

**Comment by kewbish** [comment]
Closing in favour of #524.

**Pull request closed without merging**
