### PR TITLE
Added changes discussed in meeting

### PR DESCRIPTION
**Pull request by AnimeAllstar**
- Placed course summary in card
- Added progress bar partial
- Added hr tags in between reviews
- Added note on respectful env
- Added circle icons for individual reviews

### CODE REVIEW

**Comment by AnimeAllstar** [comment]
The progress bars are experimental. Let me know what y'all thing about them. We can remove them if they aren't required.

**Review by kewbish — APPROVED** [review]
Nice, looks amazing! Thanks for taking this on.

I like the progress bars! Nit: could we add `margin-top: 0.5rem` to the `.progress` div so they have a bit more breathing room?

I also agree we should differentiate the quality and difficulty ratings in individual reviews a bit more, but I think you're right that if we add the progress bars it'll be too busy. Maybe we could add the little star/circle icons like product ratings on Amazon?

I don't think each review should be a card, because we'll get back to the problem where we can't immediately differentiate the overall course information card from the rest of the content. This layout looks good for now!

**Comment by AnimeAllstar** [comment]
@kewbish Is this good?

Screenshot 2022-12-04 at 7 28 38 AM

**Review by kewbish — APPROVED** [review]
This is great! I think we should keep the numbers besides the circles, they add some extra clarity just in case.

**Pull request merged**
