### PR TITLE
Tcf company file

### PR DESCRIPTION
**Pull request by wgervasio**

### CODE REVIEW

**Comment by wgervasio** [comment]
@kewbish Hello is it possible to review this asap, just need a link to send to employers :)

**Comment by wgervasio** [comment]
the pdf is in embedded view; worked locally but the preview doesn't seem to like it

**Review by kewbish — APPROVED** [review]
Will approve and merge for now, if the `/join-us/` URL doesn't work just send the PDF link!

**Comment by wgervasio** [comment]
thank you!!!

**Comment by kewbish** [comment]
I need to fiddle with the redirects, give me a sec!

**Comment by wgervasio** [comment]
No worries! Honestly even just hosting on the site is enough. Thanks so much 🙏🙏

**Pull request merged**
