### PR TITLE
Removed volunteer page

### PR DESCRIPTION
**Pull request by AnimeAllstar**
- commented sections that link to the volunteer page in case we need to re-add it
- deleted _index.md for the volunteer page

### CODE REVIEW

**Comment by eqfy** [comment]
I think instead of deleting it entirely, it is probably better to have a message saying that office applications are now closed, but prompt them to connect with us through our social media channels

**Comment by kewbish** [comment]
RE Eric: A potential alternative might be just to update with the 2021W volunteering Google Form too, but if the Cube isn't hiring then the alternative forms of contact would also work!

**Comment by AnimeAllstar** [comment]
re-added Volunteer page, and changed text to:

Officer applications are now closed. You can always reach out to us at [Facebook](https://www.facebook.com/ubccsss), [Twitter](https://twitter.com/ubccsss), [Reddit](https://reddit.com/r/ubccsss), or [Discord](https://discord.gg/KcQrrPz).

**Comment by RamitKataria** [comment]
If there is a fixed time of the year when the applications open or we know when we are going to open them, then we might want to add that info there as well. Like saying check back around the beginning of term 2 or beginning of next year.

**Review by eqfy — APPROVED** [review]
Looks good!

**Pull request merged**
