### PR TITLE
Updated "edit on github" button to be more obvious

### LINKED ISSUE #204: Make "Edit on Github" more obvious
Title. Objective is to encourage people to contribute, especially with the course database reviews.

### PR DESCRIPTION
**Pull request by AnimeAllstar**
**OLD**:
Screenshot 2022-12-04 at 8 07 18 AM

**NEW**:
normal:
Screenshot 2022-12-04 at 7 57 36 AM

on hover:
Screenshot 2022-12-04 at 7 57 50 AM

closes #204

### CODE REVIEW

**Comment by AnimeAllstar** [comment]
Idk if this is a good idea, but I think we should close the issue if this doesn't look good. I don't think we can make it more obvious.

**Comment by kewbish** [comment]
On a visual level, I think this is great and makes the button more noticeable!

However, I think we also could go ahead with removing the button entirely - we have a very thorough course review form now. The link also doesn't even point to the right place: it goes to the markdown file for the course instead of the YAML data file. 

There's a lot of edge cases that I think we can run into if we continue to encourage people to use GH instead of our PR form (YAML misformatting breaking builds, not including the right fields, input validation), so I'd advocate for removing the button entirely.

**Comment by AnimeAllstar** [comment]
@kewbish The button is present on several other pages like https://ubccsss.org/services/. Should we remove it everywhere?

**Comment by kewbish** [comment]
Oh I see - I missed those!

In that case I'd probably go for removing the button on the course review pages, but adding your new button design and keeping it on all other pages.

What do you think?

**Comment by AnimeAllstar** [comment]
I agree, let's wait for @argonaut0

**Comment by AnimeAllstar** [comment]
@argonaut0

**Review by argonaut0 — APPROVED** [review]
Ooop i was pinged 4 times. SORRY. Looks good though. agree with removing it from course review page since we have another method.

**Pull request merged**
