### PR TITLE
Move layouts to theme repo

### PR DESCRIPTION
**Pull request by kewbish**
This PR moves all our layouts and custom i18n translations to the theme repo (#151). 

As per our meeting, this repo will hold all content and smaller inline stylesheets or JS. I kept all assets, GitHub issues, and UBCGrades material here, as well as keeping the footer and header config files here.

Please let me know if there's anything else we'd like to switch over!

> :warning: This PR must be merged after the `ubccsss/hugo-bootstrap-5` PR is merged, so that the styles will transfer over when we build. We might need to clear the Netlify cache too, I'm not sure. The current Netlify preview won't have the styles transferred over yet, I don't think.

Related PR [here](https://github.com/ubccsss/hugo-bootstrap-5/pull/2).

Instructions for testing:
To test, clone the `ubccsss/ubccsss.org` repo and edit the `.gitmodules` to point to `kewbish/ubccsss.org` and the branch `migrate-styles`. Then run `git submodule sync` and `git submodule update --init --recursive`.

### CODE REVIEW

**Comment by eqfy** [comment]
I tried to check out this PR and run `git submodule sync ` and `git submodule update --init --recursive`. However, I am receiving the same error that I see in the netlify logs
```
Error: Error building site: "D:\git\ubccsss.org\content\about\_index.md:82:1": failed to extract shortcode: template for shortcode "calendar" not found

**Comment by kewbish** [comment]
@eqfy

I think the Netlify error is because the PR on the styling side hasn't been merged yet, but Netlify's expecting that the new theme is merged in on `master`.

Did you edit the `.gitmodules` after cloning this PR and set everything to the right branch? I forgot to include the testing instructions in this PR but:
To test, clone the `ubccsss/ubccsss.org` repo and edit the `.gitmodules` to point to `kewbish/ubccsss.org` and the branch `migrate-styles`. Then run `git submodule sync` and `git submodule update --init --recursive`.

**Comment by AnimeAllstar** [comment]
Is there any other folder we need to migrate? Like the static folder?

**Comment by kewbish** [comment]
> Is there any other folder we need to/should migrate? Like the static folder or something else? Or is there no difference in order files?

I kept both `static` and `assets` because I thought they were also 'content' in a way. Not sure if we want to move them to the other repo: `static` contains a lot of the images related to our posts, and `assets` contains some 3D cube stuff + GitHub issue script. If we moved them, it would mean that every time we wanted to update images / other smaller assets we'd have to edit the theme directly. For now, I've only moved `layouts`.

That's just my line of thinking though, we should discuss ^ more.

**Comment by eqfy** [comment]
I ended up doing a checkout of https://github.com/ubccsss/hugo-bootstrap-5/pull/2 and creating a new branch called pr-2. Probably not the best way to do it but it does let me run `hugo server` now to verify that nothing is broken. I believe if we merge in https://github.com/ubccsss/hugo-bootstrap-5/pull/2 then things should probably work.

**Review by eqfy — APPROVED** [review]

**Review by AnimeAllstar — APPROVED** [review]

**Pull request merged**
