### PR TITLE
Add TCF companies

### LINKED ISSUE #336: TCF page updates
1. Please update the list of companies attending on the tcf page to the companies [listed here](https://docs.google.com/spreadsheets/d/1ljHTyM8zIJlOoEYhWmo2Y1JdqRI_udlJGWjRcBhy37c/edit#gid=0) in column E (Company Confirmed Attendance).
2. Change the TCF 2023 text on the main flash page to Technical Career Fair 2023.

Screenshot 2022-12-24 at 7 32 11 PM

### PR DESCRIPTION
**Pull request by kewbish**
This PR closes #336 and #335.
- List of companies attending has been added. Some companies did not provide a logo, but were confirmed, so I copied something from Google. The companies also didn't provide short blurbs or specific career page application links, so for now I've copied several lines from each company's about page and used the career page links that I could find through Google. The 'contact company' button also currently links to each provided contact email from the sheet. Let me know if any of these should be changed!
- Main flash page title has been updated.
- TCF button has been moved to first position in the header and given a small box shadow.
- Add to calendar buttons have been edited.

### CODE REVIEW

**Review by AnimeAllstar — APPROVED** [review]

**Comment by kewbish** [comment]
@shubhbhalla please take a look too and LMK if anything needs to be changed when you have a moment!

**Comment by shubhbhalla** [comment]
This looks great! I just want Tommy's review on this and after he says that everything looks good, we can merge it!

**Comment by tommysteryy** [comment]
Love the work! Truly appreciate it. Loving the main page design for ubccsss.org/tcf! My only comments are as below:

- I don't think we should be displaying (if we are) the **repEmail** field. That was shared as something private.
- How are we planning to approach adding more companies? (Just for my reference)

**Comment by kewbish** [comment]
> I don't think we should be displaying (if we are) the repEmail field. That was shared as something private.

Good to know! I'll take it out of the page and purge Git history for privacy reasons too. Let me know if any companies want to add a public contact email in the future.

> How are we planning to approach adding more companies? (Just for my reference)

If you mean adding more companies to the website, it's just adding a new Markdown page in the `content/tcf` folder. It'll get auto-populated to the main page and companies list page. I can add new companies in batches whenever they confirm with you.

**Comment by kewbish** [comment]
Merging now, as comments have been addressed above! Let me know if anything else comes up or if there's any other changes to be made.

**Pull request merged**
