### PR TITLE
TCF Companies Jan 2 updates

### PR DESCRIPTION
**Pull request by wgervasio**
added kabam and icbc

### CODE REVIEW

**Comment by wgervasio** [comment]
Ready to add the company details from our spreadsheet! @kewbish

**Comment by kewbish** [comment]
@wgervasio take a look, if it looks good feel free to merge!

**Comment by wgervasio** [comment]
is it possible to remove the image background and lower the font size a bit on the company pages? Seems a bit odd to view imo. Something like just a solid color i think is nicer + a smaller font than the tcf one



image

**Comment by wgervasio** [comment]
like this seems a bit large to me
image

**Comment by wgervasio** [comment]
ok changed it 
image

**Comment by wgervasio** [comment]
ready to merge! feel free to make any changes if it breaks something! @kewbish

**Review by kewbish — APPROVED** [review]

**Pull request merged**
