### PR TITLE
Tech consulting home project

### PR DESCRIPTION
**Pull request by LenaWang03**
merged gordon and lena's branches for tech consulting

### CODE REVIEW

**Comment by kewbish** [comment]
@wgervasio ^^

**Comment by wgervasio** [comment]
Il est temps de réviser

**Comment by wgervasio** [comment]
image

Would it be possible to make the section with the projects stay in the same place, irrelevant of the size of the goals divs when they get expanded? Right now the blue shifts up and down which makes it strange. Otherwise looks great! Will need to get those final logos to you

**Comment by Hgjnnf** [comment]
> image
> 
> Would it be possible to make the section with the projects stay in the same place, irrelevant of the size of the goals divs when they get expanded? Right now the blue shifts up and down which makes it strange. Otherwise looks great! Will need to get those final logos to you

@wgervasio I guess we could hardcode the height. @kewbish @RamitKataria @LenaWang03 thoughts?

**Comment by RamitKataria** [comment]
There's probably a way to calculate what the height should be (based on the longest goal) but maybe that's overkill considering this isn't user-generated content. So yea, I think hardcoding should be fine. Maybe also set the first goal to be expanded initially?

**Comment by wgervasio** [comment]
hardcode is alright as long as it's okay enough to read on mobile tbh. If the first goal is expanded initially then that would be enough tbh.

**Comment by LenaWang03** [comment]
decided to add a bit of bottom padding to the left column instead cause that doesn't mess up the responsiveness of the page - lmk if the resizing thing is still an issue on your screens

**Comment by kewbish** [comment]
LGTM, will wait to review more thoroughly after we have the header cat replaced.

Small nit: could we fix the z-index of this menu to go on top of the cards?
image

**Comment by wgervasio** [comment]
tbh we have no pictures to replace the header with. Otherwise I can try to find a stock photo from the tcf or ai generate something

**Comment by LenaWang03** [comment]
> Small nit: could we fix the z-index of this menu to go on top of the cards? image

💀💀gordon and I discovered this issue when we were merging our stuff together and came to the conclusion that there was no quick fix. It's also an issue on the TCF page which I think this code was taken from. Will look into this more after my exams are done lol

**Pull request merged**
